/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controllers.CadastroServicoController;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author thall
 */
public class Servico extends javax.swing.JFrame {

    // Frames
    private final CadastroServicoController controller;
    JFrame frame = this;
    /**
     * Creates new form Servico
     */
    public Servico() {
        initComponents();
        
        // Controlador
        controller = new CadastroServicoController(this);
        
        // Configura Janela
        configuracaoJanela();
        
        // Atualizar janelas
        this.controller.atualizarTabela();
        
        // Travar Fechamento
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        // Adiciona um WindowListener para detectar o fechamento da janela
        addWindowListener(new WindowAdapter() 
        {
            @Override
            public void windowClosing(WindowEvent e) 
            {
                // Exibe um diálogo de confirmação
                int confirmed = JOptionPane.showConfirmDialog(
                        null, 
                        "Tem certeza que deseja sair?", 
                        "Confirmação de Saída",
                        JOptionPane.YES_NO_OPTION);

                if (confirmed == JOptionPane.YES_OPTION) {
                    // Fecha todas as janelas e sai do aplicativo
                    //dispose();
                    System.exit(0);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoDeletar = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        botaoSair2 = new javax.swing.JButton();
        botaoAdicionar = new javax.swing.JButton();
        textValor = new javax.swing.JTextField();
        labelServico = new javax.swing.JLabel();
        textServico = new javax.swing.JTextField();
        labelValor = new javax.swing.JLabel();
        tabela = new javax.swing.JScrollPane();
        jTabelaInfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoDeletar.setBackground(java.awt.Color.darkGray);
        botaoDeletar.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        botaoDeletar.setForeground(new java.awt.Color(255, 102, 51));
        botaoDeletar.setText("REMOVER SERVIÇO");
        botaoDeletar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        botaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletarActionPerformed(evt);
            }
        });

        botaoAtualizar.setBackground(java.awt.Color.darkGray);
        botaoAtualizar.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        botaoAtualizar.setForeground(new java.awt.Color(255, 102, 51));
        botaoAtualizar.setText("ATUALIZAR SERVIÇO");
        botaoAtualizar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });

        botaoSair2.setBackground(java.awt.Color.darkGray);
        botaoSair2.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        botaoSair2.setForeground(new java.awt.Color(255, 102, 51));
        botaoSair2.setText("SAIR");
        botaoSair2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        botaoSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSair2ActionPerformed(evt);
            }
        });

        botaoAdicionar.setBackground(java.awt.Color.darkGray);
        botaoAdicionar.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        botaoAdicionar.setForeground(new java.awt.Color(255, 102, 51));
        botaoAdicionar.setText("ADICIONAR");
        botaoAdicionar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        textValor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textValorActionPerformed(evt);
            }
        });

        labelServico.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelServico.setForeground(java.awt.Color.black);
        labelServico.setText("Tipo do serviço");

        textServico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textServico.setText("Tipo de serviço");
        textServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textServicoActionPerformed(evt);
            }
        });

        labelValor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelValor.setForeground(java.awt.Color.black);
        labelValor.setText("Preço");

        jTabelaInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id do serviço", "Tipo do serviço", "Preço do serviço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaInfoMouseClicked(evt);
            }
        });
        tabela.setViewportView(jTabelaInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelServico, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textServico, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textValor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoDeletar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(botaoAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoSair2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelServico, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textServico, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(textValor))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoSair2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textServicoActionPerformed

    private void textValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textValorActionPerformed

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        this.controller.inserirServico();
        this.controller.limparCamposServico();
        this.controller.atualizarTabela();
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void botaoSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSair2ActionPerformed
        this.frame.dispose();
    }//GEN-LAST:event_botaoSair2ActionPerformed

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
        this.controller.atualizarServicoTabela();
        this.controller.atualizarTabela();
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    private void botaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletarActionPerformed
       this.controller.deletarServicoTabela();
       this.controller.atualizarTabela();
    }//GEN-LAST:event_botaoDeletarActionPerformed

    private void jTabelaInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaInfoMouseClicked
        int linha = getjTabelaInfo().getSelectedRow();        
        textServico.setText(getjTabelaInfo().getValueAt(linha, 1).toString());
        textValor.setText(getjTabelaInfo().getValueAt(linha, 2).toString());
    }//GEN-LAST:event_jTabelaInfoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servico().setVisible(true);
            }
        });
    }

    public JTextField getTextServico() {
        return textServico;
    }

    public void setTextServico(JTextField textServico) {
        this.textServico = textServico;
    }

    public JTextField getTextValor() {
        return textValor;
    }

    public void setTextValor(JTextField textValor) {
        this.textValor = textValor;
    }

    public JTable getjTabelaInfo() {
        return jTabelaInfo;
    }

    public void setjTabelaInfo(JTable jTabelaInfo) {
        this.jTabelaInfo = jTabelaInfo;
    }

    public JScrollPane getTabela() {
        return tabela;
    }

    public void setTabela(JScrollPane tabela) {
        this.tabela = tabela;
    }

    
       
    public void configuracaoJanela(){
        
        // Titulo
        frame.setTitle("Cadastro de serviços");
        
        // Tamanho    
        int labelWidth = 800;  // Obtém a largura preferida da JLabel
        int labelHeight = 550;
        frame.setSize(labelWidth, labelHeight); 
        
        // Carrega o ícone e define para o JFrame
        ImageIcon icon = new ImageIcon(Main.class.getResource("/view/imagens/icons/cliente32-icon.png")); // Substitua pelo caminho do seu ícone
        frame.setIconImage(icon.getImage()); // Define o ícone da janela
               
        // Impede o redimensionamento
        frame.setResizable(false); 

        // Configura a operação de fechamento
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        // Resetar Frame
        frame.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                frame.setLocationRelativeTo(null);
                frame.setSize(labelWidth, labelHeight); 
            }
            @Override
            public void componentMoved(ComponentEvent e){
                frame.setLocationRelativeTo(null);
                frame.setSize(labelWidth, labelHeight); 
            }                    
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoDeletar;
    private javax.swing.JButton botaoSair2;
    private javax.swing.JTable jTabelaInfo;
    private javax.swing.JLabel labelServico;
    private javax.swing.JLabel labelValor;
    private javax.swing.JScrollPane tabela;
    private javax.swing.JTextField textServico;
    private javax.swing.JTextField textValor;
    // End of variables declaration//GEN-END:variables
}
