/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package View;
import Controllers.CadastroUsuarioController;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author thall
 */
public class Usuario extends javax.swing.JFrame {

    // Frames
    private final CadastroUsuarioController controller;
    JFrame frame = this;
    
    /** Creates new form CadastrosClientes */
    public Usuario() 
    {
        initComponents();
        
        // Controlador
        controller = new CadastroUsuarioController(this);
        
        // Limpar Campos
        this.controller.limparCamposUsuario();
        this.controller.atualizarTabela();
        
        // Configura Janela
        configuracaoJanela();
        
        // Travar Fechamento
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        // Adiciona um WindowListener para detectar o fechamento da janela
        addWindowListener(new WindowAdapter() 
        {
            @Override
            public void windowClosing(WindowEvent e) 
            {
                // Exibe um diálogo de confirmação
                int confirmed = JOptionPane.showConfirmDialog(
                        null, 
                        "Tem certeza que deseja sair?", 
                        "Confirmação de Saída",
                        JOptionPane.YES_NO_OPTION);

                if (confirmed == JOptionPane.YES_OPTION) {
                    // Fecha todas as janelas e sai do aplicativo
                    //dispose();
                    System.exit(0);
                }
            }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textCpf = new javax.swing.JFormattedTextField();
        textNome = new javax.swing.JFormattedTextField();
        textRg = new javax.swing.JFormattedTextField();
        textDataNasc = new javax.swing.JFormattedTextField();
        textSexo = new javax.swing.JFormattedTextField();
        textSenha = new javax.swing.JFormattedTextField();
        textTelefone = new javax.swing.JFormattedTextField();
        textCep = new javax.swing.JFormattedTextField();
        textEstado = new javax.swing.JFormattedTextField();
        textBairro = new javax.swing.JFormattedTextField();
        textEndereco = new javax.swing.JFormattedTextField();
        textUsuario = new javax.swing.JFormattedTextField();
        textEmail = new javax.swing.JFormattedTextField();
        botaoSair = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        botaoDeletar = new javax.swing.JButton();
        labelEmail1 = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        labelSexo = new javax.swing.JLabel();
        labelRG = new javax.swing.JLabel();
        labelDataNasc = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelCep = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        labelBairro = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        labelEndereco = new javax.swing.JLabel();
        tabelaS = new javax.swing.JScrollPane();
        tabelaUsers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textCpf.setBackground(java.awt.Color.darkGray);
        textCpf.setForeground(java.awt.Color.lightGray);
        try {
            textCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("222.222.222-22")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textCpf.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        textCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCpfActionPerformed(evt);
            }
        });

        textNome.setBackground(java.awt.Color.darkGray);
        textNome.setForeground(java.awt.Color.lightGray);
        textNome.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });

        textRg.setBackground(java.awt.Color.darkGray);
        textRg.setForeground(java.awt.Color.lightGray);
        try {
            textRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("222222222-22")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textRg.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        textDataNasc.setBackground(java.awt.Color.darkGray);
        textDataNasc.setForeground(java.awt.Color.lightGray);
        try {
            textDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("22/22/2222")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textDataNasc.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        textSexo.setBackground(java.awt.Color.darkGray);
        textSexo.setForeground(java.awt.Color.lightGray);
        textSexo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        textSenha.setBackground(java.awt.Color.darkGray);
        textSenha.setForeground(java.awt.Color.lightGray);
        try {
            textSenha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("**********")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textSenha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        textTelefone.setBackground(java.awt.Color.darkGray);
        textTelefone.setForeground(java.awt.Color.lightGray);
        try {
            textTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(00) 99999-9999")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textTelefone.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        textCep.setBackground(java.awt.Color.darkGray);
        textCep.setForeground(java.awt.Color.lightGray);
        try {
            textCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("00000-000")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textCep.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        textCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCepActionPerformed(evt);
            }
        });

        textEstado.setBackground(java.awt.Color.darkGray);
        textEstado.setForeground(java.awt.Color.lightGray);
        textEstado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        textBairro.setBackground(java.awt.Color.darkGray);
        textBairro.setForeground(java.awt.Color.lightGray);
        textBairro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        textEndereco.setBackground(java.awt.Color.darkGray);
        textEndereco.setForeground(java.awt.Color.lightGray);
        textEndereco.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        textUsuario.setBackground(java.awt.Color.darkGray);
        textUsuario.setForeground(java.awt.Color.lightGray);
        textUsuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        textUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsuarioActionPerformed(evt);
            }
        });

        textEmail.setBackground(java.awt.Color.darkGray);
        textEmail.setForeground(java.awt.Color.lightGray);
        textEmail.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        botaoSair.setBackground(java.awt.Color.darkGray);
        botaoSair.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        botaoSair.setForeground(new java.awt.Color(255, 102, 51));
        botaoSair.setText("SAIR");
        botaoSair.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        botaoCadastrar.setBackground(java.awt.Color.darkGray);
        botaoCadastrar.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        botaoCadastrar.setForeground(new java.awt.Color(255, 102, 51));
        botaoCadastrar.setText("CADASTRAR");
        botaoCadastrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoAtualizar.setBackground(java.awt.Color.darkGray);
        botaoAtualizar.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        botaoAtualizar.setForeground(new java.awt.Color(255, 102, 51));
        botaoAtualizar.setText("ATUALIZAR");
        botaoAtualizar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });

        botaoDeletar.setBackground(java.awt.Color.darkGray);
        botaoDeletar.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        botaoDeletar.setForeground(new java.awt.Color(255, 102, 51));
        botaoDeletar.setText("DELETAR");
        botaoDeletar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        botaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletarActionPerformed(evt);
            }
        });

        labelEmail1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelEmail1.setForeground(java.awt.Color.black);
        labelEmail1.setText("Usuário");

        labelSenha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelSenha.setForeground(java.awt.Color.black);
        labelSenha.setText("Senha de acesso");

        labelCpf.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelCpf.setForeground(java.awt.Color.black);
        labelCpf.setText("CPF");

        labelSexo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelSexo.setForeground(java.awt.Color.black);
        labelSexo.setText("Sexo");

        labelRG.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelRG.setForeground(java.awt.Color.black);
        labelRG.setText("RG");

        labelDataNasc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelDataNasc.setForeground(java.awt.Color.black);
        labelDataNasc.setText("Data de nascimento");

        labelEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelEmail.setForeground(java.awt.Color.black);
        labelEmail.setText("Email");

        labelNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelNome.setForeground(java.awt.Color.black);
        labelNome.setText("Nome completo");

        labelCep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelCep.setForeground(java.awt.Color.black);
        labelCep.setText("Cep");

        labelEstado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelEstado.setForeground(java.awt.Color.black);
        labelEstado.setText("Estado");

        labelBairro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelBairro.setForeground(java.awt.Color.black);
        labelBairro.setText("Bairro");

        labelTelefone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelTelefone.setForeground(java.awt.Color.black);
        labelTelefone.setText("Telefone");

        labelEndereco.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelEndereco.setForeground(java.awt.Color.black);
        labelEndereco.setText("Endereço");

        tabelaUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaUsersMouseClicked(evt);
            }
        });
        tabelaS.setViewportView(tabelaUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(labelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textEndereco)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textBairro))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(labelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(labelCep, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(textCep, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(labelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textRg, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(labelRG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(labelEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(textSenha))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelSenha)
                                        .addGap(14, 14, 14))))
                            .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textSexo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(labelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(109, 109, 109))))
                            .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(botaoDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(tabelaS, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(46, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelRG, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textRg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEmail1)
                            .addComponent(labelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelCep, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textCep, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)))
                        .addComponent(labelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(textEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tabelaS))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCpfActionPerformed

    private void textCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCepActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        this.frame.dispose();
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        this.controller.inserirUsuario();
        this.controller.limparCamposUsuario();
        this.controller.atualizarTabela();
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
        this.controller.atualizarCadastroUsuario();
        this.controller.atualizarTabela();  
        this.controller.limparCamposUsuario();
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    private void textUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuarioActionPerformed

    private void botaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletarActionPerformed
        this.controller.deletarUsuario();
        this.controller.atualizarTabela();
        this.controller.limparCamposUsuario();
    }//GEN-LAST:event_botaoDeletarActionPerformed

    private void tabelaUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaUsersMouseClicked
        this.controller.clicktabelaupdate();        
    }//GEN-LAST:event_tabelaUsersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoDeletar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCep;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelDataNasc;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmail1;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelRG;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JScrollPane tabelaS;
    private javax.swing.JTable tabelaUsers;
    private javax.swing.JFormattedTextField textBairro;
    private javax.swing.JFormattedTextField textCep;
    private javax.swing.JFormattedTextField textCpf;
    private javax.swing.JFormattedTextField textDataNasc;
    private javax.swing.JFormattedTextField textEmail;
    private javax.swing.JFormattedTextField textEndereco;
    private javax.swing.JFormattedTextField textEstado;
    private javax.swing.JFormattedTextField textNome;
    private javax.swing.JFormattedTextField textRg;
    private javax.swing.JFormattedTextField textSenha;
    private javax.swing.JFormattedTextField textSexo;
    private javax.swing.JFormattedTextField textTelefone;
    private javax.swing.JFormattedTextField textUsuario;
    // End of variables declaration//GEN-END:variables

         
    public void configuracaoJanela(){
        
        // Titulo
        frame.setTitle("Cadastro de usuários");
        
        // Tamanho    
        int labelWidth = 855;  // Obtém a largura preferida da JLabel
        int labelHeight = 700;
        frame.setSize(labelWidth, labelHeight); 
        
        // Carrega o ícone e define para o JFrame
        ImageIcon icon = new ImageIcon(Main.class.getResource("/view/imagens/icons/cliente32-icon.png")); // Substitua pelo caminho do seu ícone
        frame.setIconImage(icon.getImage()); // Define o ícone da janela
               
        // Impede o redimensionamento
        frame.setResizable(false); 

        // Configura a operação de fechamento
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        // Resetar Frame
        frame.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                frame.setLocationRelativeTo(null);
                frame.setSize(labelWidth, labelHeight); 
            }
            @Override
            public void componentMoved(ComponentEvent e){
                frame.setLocationRelativeTo(null);
                frame.setSize(labelWidth, labelHeight); 
            }                    
        });
    }

    public JFormattedTextField getTextBairro() {
        return textBairro;
    }

    public void setTextBairro(JFormattedTextField textBairro) {
        this.textBairro = textBairro;
    }

    public JFormattedTextField getTextCep() {
        return textCep;
    }

    public void setTextCep(JFormattedTextField textCep) {
        this.textCep = textCep;
    }

    public JFormattedTextField getTextCpf() {
        return textCpf;
    }

    public void setTextCpf(JFormattedTextField textCpf) {
        this.textCpf = textCpf;
    }

    public JFormattedTextField getTextDataNasc() {
        return textDataNasc;
    }

    public void setTextDataNasc(JFormattedTextField textDataNasc) {
        this.textDataNasc = textDataNasc;
    }

    public JFormattedTextField getTextEmail() {
        return textEmail;
    }

    public void setTextEmail(JFormattedTextField textEmail) {
        this.textEmail = textEmail;
    }

    public JFormattedTextField getTextEndereco() {
        return textEndereco;
    }

    public void setTextEndereco(JFormattedTextField textEndereco) {
        this.textEndereco = textEndereco;
    }

    public JFormattedTextField getTextEstado() {
        return textEstado;
    }

    public void setTextEstado(JFormattedTextField textEstado) {
        this.textEstado = textEstado;
    }

    public JFormattedTextField getTextNome() {
        return textNome;
    }

    public void setTextNome(JFormattedTextField textNome) {
        this.textNome = textNome;
    }

    public JFormattedTextField getTextRg() {
        return textRg;
    }

    public void setTextRg(JFormattedTextField textRg) {
        this.textRg = textRg;
    }

    public JFormattedTextField getTextSenha() {
        return textSenha;
    }

    public void setTextSenha(JFormattedTextField textSenha) {
        this.textSenha = textSenha;
    }

    public JFormattedTextField getTextSexo() {
        return textSexo;
    }

    public void setTextSexo(JFormattedTextField textSexo) {
        this.textSexo = textSexo;
    }

    public JFormattedTextField getTextTelefone() {
        return textTelefone;
    }

    public void setTextTelefone(JFormattedTextField textTelefone) {
        this.textTelefone = textTelefone;
    }

    public JFormattedTextField getTextUsuario() {
        return textUsuario;
    }

    public void setTextUsuario(JFormattedTextField textUsuario) {
        this.textUsuario = textUsuario;
    }

    public JScrollPane getTabelaS() {
        return tabelaS;
    }

    public void setTabelaS(JScrollPane tabelaS) {
        this.tabelaS = tabelaS;
    }

    public JTable getTabelaUsers() {
        return tabelaUsers;
    }

    public void setTabelaUsers(JTable tabelaUsers) {
        this.tabelaUsers = tabelaUsers;
    }    
}
